import { inferQuestCategory } from "./inferQuestCategory.ts";
import { createEpic, type Epic } from "./epic.ts";
import {
  disciplineRewardsForDifficulty,
  epicIntensityNote,
  questProfileForDifficulty,
  type Difficulty,
} from "./difficulty.ts";
import { createCheckDiscipline, type CheckDiscipline } from "./discipline.ts";
import { createQuest, type Quest } from "./quest.ts";

export type { Difficulty };

/** A named item the player rated for difficulty during intake. */
export interface IntakeRatedItem {
  title: string;
  difficulty: Difficulty;
}

/** Raw answers collected during mentor conversation. */
export interface IntakeProfile {
  playerName: string;
  /** Goals and direction — what the player is working toward. */
  northStar: string;
  blockers: string;
  /** Daily habits the player keeps or wants to build (free text). */
  dailyHabits: string;
  /** Generated by Soren from the answers above — confirmed at review. */
  epics: IntakeRatedItem[];
  quests: IntakeRatedItem[];
  disciplines: IntakeRatedItem[];
  /** Legacy field — no longer collected during intake. */
  resistance: string;
}

export interface StarterPack {
  epics: Epic[];
  quests: Quest[];
  disciplines: CheckDiscipline[];
  /** Quest ids to assign on Current Quests tab (max 3 minor). */
  assignedQuestIds: string[];
}

export { inferCategory, inferQuestCategory } from "./inferQuestCategory.ts";
export type { QuestCategoryContext } from "./inferQuestCategory.ts";

export function emptyIntake(): IntakeProfile {
  return {
    playerName: "",
    northStar: "",
    blockers: "",
    dailyHabits: "",
    epics: [],
    quests: [],
    disciplines: [],
    resistance: "",
  };
}

export function buildStarterPack(
  intake: IntakeProfile,
  existingQuestIds: Set<string>,
  existingEpicNames: Set<string>,
  existingDisciplineIds: Set<string>,
): StarterPack {
  const epics: Epic[] = [];
  const epicNameSet = new Set(existingEpicNames);

  for (const item of intake.epics) {
    const name = item.title.trim();
    if (!name) continue;
    const description = [
      intake.northStar.slice(0, 100) || name,
      epicIntensityNote(item.difficulty),
    ]
      .filter(Boolean)
      .join(" · ");
    try {
      const epic = createEpic(name, description, epicNameSet);
      epics.push(epic);
      epicNameSet.add(epic.name.toLowerCase());
    } catch {
      // skip duplicate / invalid
    }
  }

  const quests: Quest[] = [];
  const questIds = new Set(existingQuestIds);
  const firstEpic = epics[0]?.name;

  for (const item of intake.quests) {
    const title = item.title.trim();
    if (!title) continue;
    const profile = questProfileForDifficulty(item.difficulty);
    try {
      const quest = createQuest(
        {
          title,
          scale: profile.scale,
          track: "main",
          category: inferQuestCategory(title, {
            storylineTitle: epics.length === 1 ? firstEpic : undefined,
            storylineDescription: intake.northStar,
          }),
          unlockLevel: profile.unlockLevel,
          xp: profile.xp,
          epic: epics.length === 1 ? firstEpic : undefined,
        },
        questIds,
      );
      quests.push(quest);
      questIds.add(quest.id);
    } catch {
      // skip
    }
  }

  const northStar = intake.northStar.trim();
  if (northStar && intake.quests.length === 0) {
    const horizonProfile = questProfileForDifficulty("legendary");
    try {
      const horizon = createQuest(
        {
          title: northStar,
          scale: horizonProfile.scale,
          track: "main",
          category: inferQuestCategory(northStar, { storylineDescription: northStar }),
          unlockLevel: horizonProfile.unlockLevel,
          xp: horizonProfile.xp,
          epic: epics.length === 1 ? firstEpic : undefined,
        },
        questIds,
      );
      quests.push(horizon);
    } catch {
      // skip
    }
  }

  const disciplines: CheckDiscipline[] = [];
  const disciplineIds = new Set(existingDisciplineIds);

  for (const item of intake.disciplines) {
    const title = item.title.trim();
    if (!title) continue;
    try {
      const discipline = createCheckDiscipline(
        title,
        disciplineRewardsForDifficulty(item.difficulty),
        disciplineIds,
      );
      disciplines.push(discipline);
      disciplineIds.add(discipline.id);
    } catch {
      // skip
    }
  }

  const assignedQuestIds = quests
    .filter((q) => q.scale === "minor")
    .slice(0, 3)
    .map((q) => q.id);

  return { epics, quests, disciplines, assignedQuestIds };
}
